# -*- coding: utf-8 -*-
"""ProductRatings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciqth149Gr9nQSX1n7xk8siHEHAjang7

**Import Dataset**
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')

path = "/content/drive/MyDrive/Data Analysis/Apple Sales/"
df = pd.read_csv(path + "AppleSales.csv")

df

df.describe()

"""Hanya angka yang ambil di kolom RAM"""

df['Ram'] = df['Ram'].str.extract('(\d+)')

"""**Exploratory  Data Analyisis (EDA)**

**Top 10 Iphone**
"""

top_rate = df.sort_values(by=["Star Rating"], ascending=False)
top_rate = top_rate.head(10)
print(top_rate["Product Name"])

"""**Tipe Dengan Rating Tertinggi**"""

import plotly.express as px
import plotly.graph_objects as go

top4 = top_rate.sort_values(by="Number Of Ratings", ascending=False).head(4)

figure = px.bar(
    top4,
    x="Product Name",
    y="Number Of Ratings",
    text="Number Of Ratings",
    title="Top 4 Tipe iPhone dengan Rating Terbanyak",
    color="Product Name"
)


figure.update_traces(textposition='outside')
figure.show()

"""**Jumlah Review Terbanyak**"""

import plotly.express as px

top4 = (
    top_rate.groupby("Product Name")["Number Of Reviews"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
)

figure = px.pie(
    values=top4
  .values,
    names=top4
  .index,
    title="Top 3 Tipe iPhone Dengan Reviews Terbanyak"
)

figure.update_traces(
    textinfo='percent+value',
    textposition='inside'
)

figure.show()

"""**Profilling**"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install ydata_profiling

from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Profiling Report", explorative=True)

profile.to_file("EDA.html")

file_path = "/content/drive/MyDrive/Data Analysis/Apple Sales/EDA.html"

from google.colab import files
profile.to_file(file_path)

files.download(file_path)

"""**Pemodelan**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt


# fitur & target
X = df[['Sale Price', 'Discount Percentage', 'Number Of Reviews', 'Ram']]
y = df['Star Rating']

# split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# feature importance
importance = pd.Series(model.feature_importances_, index=X.columns)
importance = importance.sort_values()

# visualisasi
importance.plot(kind='barh',color=['red', 'blue', 'green', 'orange'])
plt.title("Faktor yang Mempengaruhi Ratings Product")
plt.show()

"""**Evaluasi Model**"""

from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))